version: "2"
services:
  ionic-app:
    container_name: ionic-app
     
    working_dir: /app
    command: ionic serve
    volumes: 
      - ./src:/app/src
    ports: 
      - 8100:8100
      - 35729:35729
    build: . 
    tty: true